### ISSUE TITLE
[New Application]  Nicolas Taveira

### ISSUE THREAD

**Issue by nicolasgabrielt** [thumbor/thumbor-bootcamp#22]
**How do you want to be called:** 
nicolastaveira
**Pronouns:** (e.g. He/Him/His)
He/Him/His

**What do you expect to take from this experience:**

- I want to learn more about how an open-source project works and level up my python skills. 
- I want to make networking with great engineers because I believe that networking is what moves the world. 
- One of my goals also is to work more with technologies for distributed systems like docker, redis, Kubernetes, distributed event streaming platform, etc.
- I believe that working in open-source projects will develop skills necessary to be an Engineer Manager in the future.

**Brief Summary of You (career, skills, areas of interest)**:
3y of software engineering, mostly in the back-end but I like to understand about the product and the features end-to-end, because of this I am also interested in front-end. My favorite language is python and one of my strengths as a software engineer is my knowledge about data structures and algorithms and my communication skills.

**Daily Availability (hs):** (e.g. 2h per day to work on Thumbor, or 5h a week, just an idea)
4 hours week

**Comment by heynemann** [comment]
Great!!! Welcome aboard @nicolasgabrielt! Just pick a L1 task whenever you feel like and tell me if you need any help! Just a reminder, [these are the L1 tasks](https://github.com/thumbor/thumbor-bootcamp/issues?q=is%3Aopen+-label%3Atriage+label%3AL1+label%3Atask+no%3Aassignee).
