### ISSUE TITLE
[New Application] Cristiano Santos

### ISSUE THREAD

**Issue by cristianossd** [thumbor/thumbor-bootcamp#25]
**How do you want to be called:** Cristiano
**Pronouns:** (e.g. He/Him/His)

**What do you expect to take from this experience:**
I stopped contributing to open source for while and want to enjoy this opportunity to get closer to this environment. Also, I really like to work with python and improve my skills, face situations to extract more from language, etc.

**Brief Summary of You (career, skills, areas of interest)**:
I am a software engineer with 7y of experience with product development processes and systems design. I already worked in multiple Computer Science fields and really interested to face new, big and complex challenges. 

**Daily Availability (hs):** 4-5hrs a week

**Comment by heynemann** [comment]
Welcome!!! 🎉🎉🎉
