### ISSUE TITLE
[New Application] Arielle Lynch

### ISSUE THREAD

**Issue by ariellelynch** [thumbor/thumbor-bootcamp#26]
**How do you want to be called:** 
Arielle
**Pronouns:**
She/her

**What do you expect to take from this experience:**
I'm interested in getting started with contributing to open source and getting a chance to gain exposure to new tools and projects :)

**Brief Summary of You (career, skills, areas of interest)**:
2.5 years of experience as a software engineer working on web applications. I'm a full stack engineer but currently more focused on backend work.

**Daily Availability (hs):** 
about 5 hours per week

**Comment by heynemann** [comment]
Hey @ariellelynch great to have you onboard!!! Just pick your first task and let's get started. Thumbor has some docs on [contributing and how to configure your environment], but if the docs are lacking it is a great opportunity to contribute as well.
